services:
  - name: my-node-server
    type: web
    env: node
    rootDir: server
    buildCommand: "npm install && npm run build --prefix ../client"
    startCommand: "node index.js"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 3009
